# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app_service:
        class: AppBundle\Service\AppService
        arguments: ["@doctrine.orm.entity_manager"]

    post_service:
        class: AppBundle\Service\PostService
        arguments: ["@doctrine.orm.entity_manager"]

    portfolio_service:
        class: AppBundle\Service\PortfolioService
        arguments: ["@doctrine.orm.entity_manager"]